package.json
=> chore(package): update babel to version 6.3.13

package.json
=> chore(package): update cssnano to version 3.4.0

package.json
=> chore(package): update babel-core to version 6.3.17

package.json
=> chore(package): update babel-core to version 6.3.21

package.json
=> chore(package): update rollup to version 0.21.3

package.json
=> chore(package): update babel to version 6.3.26

package.json
=> chore(package): update rollup to version 0.22.1

package.json
=> chore(package): update rollup-plugin-npm to version 1.2.0

package.json
=> chore(package): update babel-core to version 6.4.0

package.json
=> chore(package): update rollup-plugin-npm to version 1.2.1

package.json
=> chore(package): update rollup-plugin-babel to version 2.3.8

package.json
=> chore(package): update commitizen to version 2.5.0

package.json
=> chore(package): update grunt-spritesmith to version 6.1.1

package.json
=> chore(package): update babel-preset-es2015-rollup to version 1.1.1

package.json
=> chore(package): update es6-promise to version 3.1.2

package.json
=> chore(package): update eslint to version 2.1.0

package.json
=> chore(package): update grunt-postcss to version 0.7.2

package.json
=> chore(package): update rollup to version 0.25.4

README.md
hi, we recently add your lib on https://cdnjs.com, could you please also consider adding our link?
thank you very much!
https://cdnjs.com/libraries/embed-js
https://github.com/cdnjs/cdnjs/pull/7111
=> add cdnjs link to CDN

src/js/modules/emoticons/emoji.js, src/js/modules/regex.js
Ability to render emojis with custom function.
Function should return template to paste.
Please check if making `customEmoji` as function doesn't provide any collisions. I've done global search for `customEmoji` but didn't found a thing.
Maybe we should move regexp search for external function also. To be more versatile
=> added custom render function. #197 fix

src/js/modules/template.js
Fix building, tests now pass. I think semi-colons should be allowed (and required) at end of lines, but thats personal preference.
=> fix lint errors

package.json, yarn.lock
=> fix(postinstall): install selenium while running tests
